name: Stylemode101
favicon: null
layout_spectrum: 0.67268
typography_spectrum: 0.61026
title: Style is Everything.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040404'
    - '#c1c1c1'
    - '#828281'
    - '#4b4746'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5817210676614195
purpose: []
