name: Stylemode101
favicon: null
layout_spectrum: 0.67268
typography_spectrum: 0.61026
title: STYLE MODE 101... Where Style is Everything.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#585755'
    - '#959796'
    - '#cdcfce'
    - '#fdfdfb'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5817210676614195
purpose: []
